@class  NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface FTSContactMgr : NSObject
{
    BOOL _hasInited;
    NSMutableArray *_arrFilterContact;
    NSMutableArray *_arrFilterAddressBookFriend;
    NSMutableArray *_arrNormalContact;
    NSMutableArray *_arrGroupContact;
    NSMutableArray *_arrBrandContact;
    NSString *_lastQueryText;
    NSString *_newestQueryText;
    NSMutableArray *_arrLastQueryKeywords;
    NSMutableDictionary *_dicSearchMatchTip;
    NSMutableArray *_arrGroupContactForDetailPage;
    NSMutableArray *_arrSourceGroupContact;
    NSString *_lastQueryTextForDetailPage;
    NSString *_newestQueryTextForDetailPage;
    NSMutableArray *_arrLastQueryKeywordsForDetailPage;
    NSMutableDictionary *_dicSearchMatchTipForDetailPage;
    NSMutableDictionary *_dicChinesePinYin;
    NSMutableDictionary *_dicMatchWeChatID;
    NSMutableDictionary *_dicCacheFilterContact;
    NSMutableDictionary *_dicCacheFilterAddressBookFriend;
    NSMutableArray *_arrSourceSingleContact;
    NSMutableArray *_arrSingleContactForDetailPage;
    NSMutableArray *_arrAddressBookFriendForDetailPage;
    NSMutableArray *_arrSourceBrandContact;
    NSMutableArray *_arrBrandContactForDetailPage;
    BOOL _needMonitorReport;
    BOOL _needSaveRUContact;
    NSMutableDictionary *_dicRUContact;
    int _mgrScene;
    id _ftsTopHitMgr;
}

@property(retain, nonatomic) NSArray *arrLastQueryKeywords; // @synthesize arrLastQueryKeywords=_arrLastQueryKeywords;
@property(retain, nonatomic) NSMutableArray *arrLastQueryKeywordsForDetailPage; // @synthesize arrLastQueryKeywordsForDetailPage=_arrLastQueryKeywordsForDetailPage;
- (void)asyncDetailSearch:(id)arg1 handler:(id)arg2;
- (void)asyncSearchText:(id)arg1;
- (void)asyncSearchTextForDetailPage:(id)arg1;
- (void)asyncSearchTextForDetailPageOfBrandContact:(id)arg1;
- (void)asyncSearchTextForDetailPageOfSingleContact:(id)arg1;
- (void)cacheSearchResult;
- (void)cancelSearch;
- (void)cancelSearchForDetailPage;
- (void)cancelSearchForDetailPageOfBrandContact;
- (void)cancelSearchForDetailPageOfSingleContact;
- (void)dealloc;
- (void)doInitWorker;
- (void)doSearch:(id)arg1;
- (void)doSearchForDetailPage:(id)arg1;
- (void)doSearchForDetailPageOfBrandContact:(id)arg1;
- (void)doSearchForDetailPageOfSingleContact:(id)arg1;
@property(retain, nonatomic) id ftsTopHitMgr; // @synthesize ftsTopHitMgr=_ftsTopHitMgr;
- (id)getAddressBookDictionary;
- (id)getAddressBookFriendForDetailPage:(id)arg1;
- (id)getAddressBookFriends;
- (id)getAddressBookFriendsByNickName:(id)arg1;
- (unsigned long)getAddressBookFriendsCount;
- (id)getArrSourceContact;
- (id)getBrandContacts;
- (unsigned long)getBrandContactsCount;
- (id)getBrandContactsForDetailPage:(id)arg1;
- (id)getCacheFilterAddressFriend:(id)arg1;
- (id)getCacheFilterContact:(id)arg1;
- (id)getChinesePinyin;
- (id)getContactDictionary;
- (unsigned long)getCreateTimeForUser:(id)arg1;
- (id)getDetailMatchTipForUserName:(id)arg1;
- (id)getDicSourceContact;
- (id)getGroupContacts;
- (unsigned long)getGroupContactsCount;
- (id)getGroupContactsForDetailPage:(id)arg1;
- (id)getMatchTipForUserName:(id)arg1;
- (id)getNickNameToFriendsDictionary;
- (id)getNormalContacts;
- (unsigned long)getNormalContactsCount;
- (id)getNormalContactsForDetailPage:(id)arg1;
- (id)getSingleContactsForDetailPage:(id)arg1;
- (id)getSourceAddressBook;
- (id)getSourceBrandContactForDetailPage;
- (id)getSourceFilterAddressFriend:(id)arg1;
- (id)getSourceFilterContact:(id)arg1;
- (id)getSourceGroupContactForDetailPage;
- (id)getSourceSingleContactContactForDetailPage;
- (unsigned long)getTotalCount;
- (BOOL)hasAddressBookeFriends;
- (BOOL)hasBrandContacts;
- (BOOL)hasCacheFilterAddressFriend:(id)arg1;
- (BOOL)hasCacheFilterContact:(id)arg1;
- (BOOL)hasGroupContacts;
- (BOOL)hasMatchWechatID:(id)arg1;
- (BOOL)hasNormalContacts;
- (BOOL)hasSearchDoneForDetailPage:(id)arg1;
- (BOOL)hasSearchDoneForDetailPageOfBrandContact:(id)arg1;
- (BOOL)hasSearchDoneForDetailPageOfSingleContact:(id)arg1;
- (BOOL)hasSearchResult;
- (id)init;
- (void)invalidAllAddressBookCache;
- (void)invalidAllContactCache;
- (void)invalidateDetailCache;
- (BOOL)isTopHitAddressBookReady;
- (BOOL)isTopHitContactReady;
@property(retain, nonatomic) NSString *lastQueryText; // @synthesize lastQueryText=_lastQueryText;
@property(retain, nonatomic) NSString *lastQueryTextForDetailPage; // @synthesize lastQueryTextForDetailPage=_lastQueryTextForDetailPage;
- (void)logGroupMatchTip;
- (void)logGroupMatchTipForDetailSearch;
- (void)logInfo;
@property(nonatomic) int mgrScene; // @synthesize mgrScene=_mgrScene;
- (void)monitorReport;
@property(nonatomic) BOOL needMonitorReport; // @synthesize needMonitorReport=_needMonitorReport;
@property(retain, nonatomic) NSString *newestQueryText; // @synthesize newestQueryText=_newestQueryText;
@property(retain, nonatomic) NSString *newestQueryTextForDetailPage; // @synthesize newestQueryTextForDetailPage=_newestQueryTextForDetailPage;
- (void)onAddressBookReload;
- (void)onAppTerminate;
- (void)onClearData;
- (void)onContactDeleted:(id)arg1;
- (void)onContactReload;
- (void)onContactReplaced:(id)arg1;
- (void)onEnterBackground;
- (void)onReloadData;
- (void)searchCompletely:(id)arg1;
- (void)searchTextAndNotNotify:(id)arg1;
- (void)searchTextCompletely:(id)arg1;
- (void)selectAddressFriend:(id)arg1;
- (void)selectContact:(id)arg1;
- (void)selectContact:(id)arg1 isHomePage:(BOOL)arg2;
- (void)sortAddressBookFriends:(id)arg1 matchTips:(id)arg2;
- (void)sortContacts:(id)arg1 matchTips:(id)arg2;
- (id)syncSearchTextForSingleContact:(id)arg1 limitCount:(unsigned long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end
